/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Pages30questionsRouteImport } from './routes/pages/30questions'
import { Route as PagesQuestionQuestionIdRouteImport } from './routes/pages/question.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Pages30questionsRoute = Pages30questionsRouteImport.update({
  id: '/pages/30questions',
  path: '/pages/30questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesQuestionQuestionIdRoute = PagesQuestionQuestionIdRouteImport.update({
  id: '/pages/question/$questionId',
  path: '/pages/question/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/30questions': typeof Pages30questionsRoute
  '/pages/question/$questionId': typeof PagesQuestionQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/30questions': typeof Pages30questionsRoute
  '/pages/question/$questionId': typeof PagesQuestionQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages/30questions': typeof Pages30questionsRoute
  '/pages/question/$questionId': typeof PagesQuestionQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages/30questions' | '/pages/question/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages/30questions' | '/pages/question/$questionId'
  id: '__root__' | '/' | '/pages/30questions' | '/pages/question/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Pages30questionsRoute: typeof Pages30questionsRoute
  PagesQuestionQuestionIdRoute: typeof PagesQuestionQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/30questions': {
      id: '/pages/30questions'
      path: '/pages/30questions'
      fullPath: '/pages/30questions'
      preLoaderRoute: typeof Pages30questionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/question/$questionId': {
      id: '/pages/question/$questionId'
      path: '/pages/question/$questionId'
      fullPath: '/pages/question/$questionId'
      preLoaderRoute: typeof PagesQuestionQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Pages30questionsRoute: Pages30questionsRoute,
  PagesQuestionQuestionIdRoute: PagesQuestionQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
